repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Whitespace & formatting
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: mixed-line-ending

      # File content checks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict

      # Size checks
      - id: check-added-large-files
        args: ['--maxkb=100']

      # Repo / Git safety
      - id: no-commit-to-branch
      - id: forbid-new-submodules
        args: ['--submodule-type=git']

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ['--profile', 'black']

  # Linting & static analysis
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        files: \.py$

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ['--line-length', '88']

  # File format checking
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(yaml|yml|md|json)$
        exclude: ^\.github/

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: ^\.github/

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        files: \.md$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: \.github/workflows/.*\.ya?ml$
