name: Update Readme Pipeline

on:
  push:
    branches: [dev]

jobs:
  update_readme:
    name: Update Readme
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Update Script
        run: |
          python scripts/update_readme.py \
            --readme="README.md"
            --bucket=jd-35656-public-collections \
            --branch=main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format README.md
        run: prettier --write README.md

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint README.md
        run: markdownlint README.md

      - name: Commit README.md if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || {
            git pull --rebase origin main
            git commit -m "chore: Update README with new CFT links"
            git push
          }
